version: "3.9"

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: community_portal
      POSTGRES_USER: nxtturn_user
      POSTGRES_PASSWORD: Airtel@123
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis
    restart: always

  backend:
    build:
      context: /home/anup_wade/nxtturn-env-ready/Loopline
    container_name: django_backend
    working_dir: /app
    command: >
      sh -c "
      python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      exec daphne -b 0.0.0.0 -p 8000 config.asgi:application
      "
    restart: always
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.prod
      ENV: prod
      POSTGRES_DB: community_portal
      POSTGRES_USER: nxtturn_user
      POSTGRES_PASSWORD: Airtel@123
      POSTGRES_HOST: db
      ALLOWED_HOSTS: localhost,127.0.0.1,34.30.48.239,nxtturn.com,www.nxtturn.com
      FRONTEND_URL: http://34.30.48.239
    volumes:
      - static_volume:/app/staticfiles

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      # ✅ Vue frontend build (STATIC FILES)
      - /home/anup_wade/nxtturn-env-ready/frontend/dist:/usr/share/nginx/html:ro

      # ✅ Django static files
      - static_volume:/app/staticfiles

      # ✅ NGINX config
      - /home/anup_wade/nxtturn-env-ready/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend

volumes:
  postgres_data:
  static_volume:

